name: Integration tests

on: [push, pull_request]

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: ["opensearch"]
        secured: ["false"]
        # Versions 1.0.x are disabled due to https://github.com/opensearch-project/project-website/issues/737
        # No plugins released for these versions, so test can't run properly
        version: [1.3.0, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - run: dotnet nuget locals all --clear
        name: Clear nuget cache
      - run: "./build.sh integrate ${{ matrix.cluster }}-${{ matrix.version }} readonly,writable random:test_only_one --report"
        name: ${{ matrix.cluster }} Integration Tests
